  # ========================================== Shared Backend Template ==========================================
  x-backend-template: &backend-template # We can now Injects the entire shared block! [DRY principle]
    networks:
      - ft_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: unless-stopped

  x-backend-env: &backend-env
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_USER: ${RABBITMQ_USER}
    RABBITMQ_PASSWORD_FILE: /run/secrets/rabbitmq_password

  services:
    # ========================================== Database ==========================================
    database:
      build:
        context: "./database"
      pull_policy: build
      image: "database"
      container_name: database
      secrets:
        - db_password
        - auth_service_password
        - club_service_password
        - notification_service_password
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        AUTH_USER: ${AUTH_USER}
        CLUB_USER: ${CLUB_USER}
        NOTIFICATION_USER: ${NOTIFICATION_USER}
        AUTH_SCHEMA: ${AUTH_SCHEMA}
        CLUB_SCHEMA: ${CLUB_SCHEMA}
        NOTIFICATION_SCHEMA: ${NOTIFICATION_SCHEMA}
        APP_ENV: ${APP_ENV}
      networks:
        - ft_network
      ports:
        - 5432:5432
      volumes:
        - database_vol:/var/lib/postgresql
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      restart: unless-stopped

    # ========================================== nginx ==========================================
    nginx:
      build:
        context: ./nginx
      image: "nginx"
      container_name: nginx
      ports:
        - 443:443
      networks:
        - bridge_network
        - ft_network
      depends_on:
        database:
          condition: service_healthy
      restart: unless-stopped

    # ========================================== Rabbitmq ==========================================
    rabbitmq:
      build:
        context: ./rabbitmq
      pull_policy: build
      image: "rabbitmq"
      container_name: rabbitmq
      secrets:
        - rabbitmq_password
      environment:
        RABBITMQ_USER: ${RABBITMQ_USER}
      ports:
        - "5672:5672" # (AMQP Protocol): This is the "Engine" port. It uses a highly efficient, binary messaging protocol
        - "15672:15672" # (HTTP Protocol): This is the "Human" port. It serves the Management UI web dashboard
      networks:
        - bridge_network
        - ft_network
      volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 20s
      restart: unless-stopped

  # ========================================== API Gateway ==========================================
    api_gateway:
      <<: *backend-template
      build:
        context: ../backend
        args:
          APP_NAME: api-gateway
      image: "api-gateway"
      container_name: api-gateway
      environment:
        <<: *backend-env
        # JWT_ACCESS_SECRET_FILE: /run/secrets/jwt_access_secret
      secrets:
        # No DB secret: the gateway has no DB
        - rabbitmq_password
        # - jwt_access_secret   


    # ========================================== Authentication ==========================================
    auth:
      <<: *backend-template
      build:
        context: ../backend
        args:
          APP_NAME: auth-service
      image: 'auth-service'
      container_name: auth-service
      environment:
        <<: *backend-env
        DB_NAME: ${DB_NAME}
        DB_USER: ${AUTH_USER}
        DB_SCHEMA: ${AUTH_SCHEMA}
        DB_PASSWORD_FILE: /run/secrets/auth_service_password
        # JWT_ACCESS_SECRET_FILE: /run/secrets/jwt_access_secret
        # JWT_ACCESS_TTL: 15m
      secrets: 
        - rabbitmq_password
        - auth_service_password
        # - jwt_access_secret

    # ========================================== Club ==========================================
    club:
      <<: *backend-template
      build:
        context: ../backend
        args:
          APP_NAME: club-service
      image: "club-service"
      container_name: club-service
      environment:
        <<: *backend-env
        DB_NAME: ${DB_NAME}
        DB_USER: ${CLUB_USER}
        DB_SCHEMA: ${CLUB_SCHEMA}
        DB_PASSWORD_FILE: /run/secrets/club_service_password
      secrets: [rabbitmq_password, club_service_password]

    # ========================================== Notification ==========================================

    notification:
      <<: *backend-template
      build:
        context: ../backend
        args:
          APP_NAME: notification-service
      image: "notification-service"
      container_name: notification-service
      environment:
        <<: *backend-env
        DB_NAME: ${DB_NAME}
        DB_USER: ${NOTIFICATION_USER}
        DB_SCHEMA: ${NOTIFICATION_SCHEMA}
        DB_PASSWORD_FILE: /run/secrets/notification_service_password
      secrets: [rabbitmq_password, notification_service_password]

    # ========================================== Frontend ==========================================
    frontend:
      build:
        context: ../frontend
      image: "frontend"
      container_name: frontend
      networks:
        - ft_network
      depends_on:
        database:
          condition: service_healthy
      restart: unless-stopped


  # ========================================== Networks, Volumes and Secrets ==========================================

  networks:
    ft_network:
      driver: bridge
      name: "ft_network"
      # internal: true // Uncomment this line for production
    bridge_network:
      driver: bridge
      name: "bridge_network"

  volumes:
    database_vol:
      name: database_vol
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '${HOME}/data/database'
    rabbitmq_vol:
      name: rabbitmq_vol
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '${HOME}/data/rabbitmq'

  secrets:
    db_password:
      file: ./secrets/db_password.txt
    auth_service_password:
      file: ./secrets/auth_service_password.txt
    club_service_password:
      file: ./secrets/club_service_password.txt
    notification_service_password:
      file: ./secrets/notification_service_password.txt
    rabbitmq_password:
      file: ./secrets/rabbitmq_password.txt
