listen_addresses = '*'       # Accessible from any IP in the ft_network
max_connections = 200        # By default, PostgreSQL allows only 100 simultaneous connections. With NestJS and WebSockets, we might exhaust this
shared_buffers = 256MB       # Memory dedicated to caching data
work_mem = 16MB              # Memory for complex sorts and JOINs